version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: miniurl:prod
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

volumes:
  pgdata_prod:
